### ISSUE TITLE
Heroku says: Source code violates the Salesforce Acceptable Use

### ISSUE THREAD

**Issue by 75asa** [seratch/jp-holidays-for-slack#1]
## Summary
It was working fine, but now, when I try to deploy app, I see message: Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

![error-message](https://user-images.githubusercontent.com/54730133/146274858-ebf0bfc1-ed95-41f9-9e44-f37013123b8e.png)

I looked at the Heroku Policy and couldn't figure out why Heroku Deploy wasn't working...

## FYI
- https://www.heroku.com/policy/aup

**Comment by seratch** [comment]
Added a workaround in README: https://github.com/seratch/jp-holidays-for-slack/commit/4dc653fc0d0e50477376ea62fd59442bfec39cf1
